version: '3.8'

services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

# nerdctl compose up -d
# heroku pg:pull HEROKU_POSTGRESQL_SILVER postgres://postgres@localhost/jalkaennustus --app jalkaennustus
# should prompt for password. If not, then try different shell